version: '3.7'

services:

  keycloak:
    # Redhat-sso 7.5 uses keycloak 15.0.2
    # https://access.redhat.com/articles/2342881#rhsso75
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - "8085:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin