# curl -v http://localhost:8080/orders
#-H 'Content-Type: application/json'
#-d '
#{
#  "items":[
#    {
#      "itemCode":"IT0001",
#      "quantity":3
#    },
#    {
#      "itemCode":"IT0004",
#      "quantity":1
#    }
#  ],
#  "shippingAddress":"福建省厦门市XX区XX街道XX小区XX栋XX室"
#}'
POST http://localhost:8080/orders
Content-Type: application/json


{
  "items":[
    {
      "itemCode":"IT0001",
      "quantity":3
    },
    {
      "itemCode":"IT0004",
      "quantity":1
    }
  ],
  "shippingAddress":"福建省厦门市XX区XX街道XX小区XX栋XX室"
}

###

curl -v http://localhost:8080/orders \
-H 'Authorization: Bearer eyJraWQiOiI0MTU1MTQ2OC0zNjUyLTQ4ZTktYjNlMy04OTYyYTRiYTAzZDUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvcmRlcnByb2Nlc3NpbmdzZXJ2aWNlIiwiYXVkIjoib3JkZXJwcm9jZXNzaW5nc2VydmljZSIsIm5iZiI6MTY1MTEyOTI5MCwic2NvcGUiOlsicmVhZCIsIm9wZW5pZCIsIndyaXRlIl0sImlzcyI6Imh0dHA6XC9cL2xvY2FsaG9zdDo4MDg1IiwiZXhwIjoxNjUxMTI5NTkwLCJpYXQiOjE2NTExMjkyOTB9.eZ2Jkwzo10qTVeMPCaJHcQy329bXky1rRcVpQlY6mzqp0EnlGac86CGp2Fz_P1GxYCrvzpqUgO2B26IMd4n2y9D1j-c3wqyndDAw7DdK673YBCpS-7_9Ovgb1q9kON0uvlLGPT4cO91_F0W2Tj6Ar6XyhiZKRmfblEYAKbNhh14-LC8l4dSwEwWtr7JzTTSmEjuFUoD955QBN3uDz3fHXW4TyRgs9zc59MEEXBCqyRETNJIOxRaRPlU-XGryHX8ntKp7UkrwbNRPLo93GUACZ9MMGTaltstbjsCnFmsULXXwam7g3cXm6HY0bqH9bWdJfYSfqkfj4diaHb_XZML7BQ'
-H 'Content-Type: application/json' \
--data-binary @- << EOF
{
  "items":[
    {
      "itemCode":"IT0001",
      "quantity":3
    },
    {
      "itemCode":"IT0004",
      "quantity":1
    }
  ],
  "shippingAddress":"福建省厦门市XX区XX街道XX小区XX栋XX室"
}
EOF
###

POST http://localhost:8080/orders
Content-Type: application/json
Authorization:  Bearer eyJraWQiOiJhYjkwMmRhOS02NDY0LTRiYjQtOWQ3NC02MjA5ODRiODQzMzYiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJlcmd1byIsImF1ZCI6Inl5aXQiLCJuYmYiOjE2NTY5ODc4NzQsInNjb3BlIjpbInJlYWQiLCJ3cml0ZSJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA4NSIsImV4cCI6MTY1Njk4ODE3NCwiaWF0IjoxNjU2OTg3ODc0fQ.eheX49wBaaBVaFpl2CPQMPkQ60i1eYZ8rkd6lG-dziDFYE5R3s2lxWGpIt_v9RQ6z-j9w32xzDpTo8chwNiP60lp8ok1C0dI8Gj2JoBiw7y1Scd-In3yegyrTs9JNyw5oI7l8vxPIRV_pGRyzPxkLl-Ch44wj2i3B2cfGEJ9Xm3K4obLcznSIUHrqO_hg_3OE5wJ3kbbsJgYtTXATzDrlCYPc1z2jETh9G4b8pTg2O22jNGLEoNw3vldAOoeG8_5c44KzIwFaIAuGkUClpri-6whhY9Wxqs_mKzBDLepMGp_P-zqVVAz5youl3E-B5gkVE6G_HxB1qqMFC7s_CkAXg

{
  "items":[
    {
      "itemCode":"IT0001",
      "quantity":3
    },
    {
      "itemCode":"IT0004",
      "quantity":1
    }
  ],
  "shippingAddress":"福建省厦门市XX区XX街道XX小区XX栋XX室"
}

###


