
POST http://localhost:9090/api/oauth2/token
Authorization: Basic b3JkZXJwcm9jZXNzaW5nc2VydmljZTpvcmRlcnByb2Nlc3NpbmdzZXJ2aWNlc2VjcmV0
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
###

POST http://localhost:9090/api/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=orderprocessingapp&client_secret=orderprocessingsecret
###



# 下订单
POST http://localhost:9090/api/orders
Authorization: Bearer eyJraWQiOiJkMmMwNzk3Yi03ZWYxLTRlNTgtYmU3NC1jNzRhMWQxNzEzYWUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvcmRlcnByb2Nlc3NpbmdzZXJ2aWNlIiwiYXVkIjoib3JkZXJwcm9jZXNzaW5nc2VydmljZSIsIm5iZiI6MTY1MjI2MDQyNSwic2NvcGUiOlsicmVhZCIsIm9wZW5pZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA4NSIsImV4cCI6MTY1MjI2MDcyNSwiaWF0IjoxNjUyMjYwNDI1fQ.M8Vl15ksztAu3Xm28RYKol2jQ8fpVaOpbijL_Qla3_4v-TS2L6T6eBc9uxVJjKZ-FuV6Wq71ttGxPs_5DASBIW5RoVApPyq3S7Xh3DLrJThI4d1XZIQH4rCW0KxLARssQPODt6AsbYgoJr19Fxp7iYlkzy-lbu63Jkgql3bsXmxz3WGP3cvW1EYN6gg5jJJbp98X78Q_3A8jvBxLc620Hz2rTPsnt9TDgOrOkjRhxi6lxjcNVvSO171hEuhYLZzYR3QZw1oHr9V5uYDGcg4Kk4-ARK-Af-zFAMefeIkebQGTw2xfb_r99c9KJdiP0c0GP9Mlg6Ws7IasXnHrcxtTfQ
Content-Type: application/json

{
  "items":[
    {
      "itemCode":"IT0001",
      "quantity":3
    },
    {
      "itemCode":"IT0004",
      "quantity":1
    }
  ],
  "shippingAddress":"福建省厦门市XX区XX街道XX小区XX栋XX室"
}

###

# 查询订单
GET http://localhost:9090/api/orders/ba078f37-a29a-4322-b081-1d0cee2bebdc
Authorization: Bearer eyJraWQiOiJkMmMwNzk3Yi03ZWYxLTRlNTgtYmU3NC1jNzRhMWQxNzEzYWUiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvcmRlcnByb2Nlc3NpbmdzZXJ2aWNlIiwiYXVkIjoib3JkZXJwcm9jZXNzaW5nc2VydmljZSIsIm5iZiI6MTY1MjI2MDQyNSwic2NvcGUiOlsicmVhZCIsIm9wZW5pZCJdLCJpc3MiOiJodHRwOlwvXC9sb2NhbGhvc3Q6ODA4NSIsImV4cCI6MTY1MjI2MDcyNSwiaWF0IjoxNjUyMjYwNDI1fQ.M8Vl15ksztAu3Xm28RYKol2jQ8fpVaOpbijL_Qla3_4v-TS2L6T6eBc9uxVJjKZ-FuV6Wq71ttGxPs_5DASBIW5RoVApPyq3S7Xh3DLrJThI4d1XZIQH4rCW0KxLARssQPODt6AsbYgoJr19Fxp7iYlkzy-lbu63Jkgql3bsXmxz3WGP3cvW1EYN6gg5jJJbp98X78Q_3A8jvBxLc620Hz2rTPsnt9TDgOrOkjRhxi6lxjcNVvSO171hEuhYLZzYR3QZw1oHr9V5uYDGcg4Kk4-ARK-Af-zFAMefeIkebQGTw2xfb_r99c9KJdiP0c0GP9Mlg6Ws7IasXnHrcxtTfQ
###
