POST http://localhost:9090/api/oauth2/token
Authorization: Basic b3JkZXJwcm9jZXNzaW5nc2VydmljZTpvcmRlcnByb2Nlc3NpbmdzZXJ2aWNlc2VjcmV0
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
###

POST http://localhost:9090/api/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&client_id=orderprocessingapp&client_secret=orderprocessingsecret
###